version: '3.8'

services:
  ms_stock:
    image: ms_stock:latest
    ports:
      - 5000:5000
    environment:
      - FLASK_CONTEXT=development
      - DATABASE_URL=postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_db
    networks:
      - mired
    depends_on:
      - db

  ms_compras:
    image: ms_compras:latest
    ports:
      - 5001:5001
    environment:
      - FLASK_CONTEXT=development
      - DATABASE_URL=postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_db
    networks:
      - mired
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: main_app_user
      POSTGRES_PASSWORD: main_app_password
      POSTGRES_DB: main_app_db
    ports:
      - "5433:5432"
    networks:
      - mired
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


networks:
  mired:
    driver: bridge
