version: '3.8' # Asegúrate de especificar la versión

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: main_app_user
      POSTGRES_PASSWORD: main_app_password
      POSTGRES_DB: main_app_db
    ports:
      - "5433:5432"
    networks:
      - mired
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # Montar el archivo de inicialización

  ms_stock:
    build:
      context: ../ms-inventarios # Ruta hacia el microservicio
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_db
      DATABASE_TEST_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_test_db
      DATABASE_PROD_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_prod_db
      SQLALCHEMY_ENGINE_OPTIONS: |
        {"connect_args": {"options": "-csearch_path=stock_schema"}}
    networks:
      - mired

  ms_compras:
    build:
      context: ../ms-compras # Ruta hacia el microservicio
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_db
      DATABASE_TEST_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_test_db
      DATABASE_PROD_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_prod_db
      SQLALCHEMY_ENGINE_OPTIONS: |
        {"connect_args": {"options": "-csearch_path=compras_schema"}}
    networks:
      - mired

volumes:
  postgres_data:


networks:
  mired:
    driver: bridge
